language: node_js

sudo: false

node_js:
  - "9"

script:
  - node --version
  - yarn --version
  - yarn run build
  - yarn run test
  - yarn run coverage 

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - master
    - /^greenkeeper/.*$/
